### ISSUE TITLE
Initialize-OnPremDSTGroupToCloud Could not find a part of the path

### ISSUE THREAD

**Issue by tknoblock1** [PhilipHaglund/DistributionGroupMigration#4]
After hours of searching how to migrate DST Groups from on-prem Exchange to O365 that can't be upgraded, I found this module for performing this. I've installed in using Powershell 7 and I keep running into the issue that the command "Could not find a part of the path 'C:\Users\<user>\AppData\Local\Temp\tmp_j1epa252.kbf\tmp_j1epa252.kbf.format.ps1xml'. This occurs right after entering Exchange On-Premise credentials and it runs through creating a PSSession

Any ideas? that path doesn't even exist on my machine

**Comment by tknoblock1** [comment]
Now somehow, after manually creating the temp folder and file path, I get the error 'Object reference not set to an instance of an object'. Isn't this module supposed to create all of this all on it's own?

**Comment by PhilipHaglund** [comment]
Hi @tknoblock1, unfortunatlly I haven't had the time to maintain this repository. 
So connections to Exchange Online needs to be updated using the ExchangeOnlineManagement module.

I'll see if i can find the time to update the module, but can't promise anything.

**Comment by tknoblock1** [comment]
Thanks @PhilipHaglund do you recommend some other way to perform the migration aside from using the module?

**Comment by tknoblock1** [comment]
also, could you explain how the module checks for who manages the group? I'm getting repeating errors that the member who manages the group doesn't exist in Exchange Online, even though I've migrated groups already who are managed by the same user who does exist in Exchange Online

**Comment by PhilipHaglund** [comment]
Hmm, I've not found any other way than coping using the same attributes like this modules does. 

Regarding the "missing" managers I think there are some validation issues/bugs inside the code.
